
#1.项目启动的端口
server:
  port: 8080

#2.数据库连接参数
jdbc:
  driver: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://10.211.55.5:3306/point?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
  username: root
  password: bigdata

#3.Mybatis配置
mybatis:
  config:
    location: mybatis-config.xml
mapper.path: /dao/*.xm
entity:
  package: /entity/*

#4.Eureka client的配置
spring:
  application:
    name: mybatis
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/
